### ISSUE TITLE
some debug  info must not  disable in 6.2 release 

### ISSUE THREAD

**Issue by armgong** [royqh1979/Dev-CPP#102]
<img width="457" alt="捕获" src="https://user-images.githubusercontent.com/4819374/101980090-f00f5200-3c9d-11eb-8633-185bc814cb17.PNG">

cann't create file f:\tokens.txt

IMHO , better use $IFDEF DEBUG $IFDEF RELEASE for debug and release , otherwise this will happen again

**Comment by armgong** [comment]
it is portable version

**Comment by royqh1979** [comment]
Thanks for the bug report. I'll release 6.2.1 as soon as possible

**Comment by armgong** [comment]
thanks , now close
