### ISSUE TITLE
在代码着色设置界面操作时部分着色项目随机变成其它颜色

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#106]
版本是6.2.1，在左边的列表或右边的示例中点击切换项目时，会随机地使部分项目变成其它颜色。光标在示例窗口按住快速拖动时能很明显地看到现象。
设置是从旧版本保留下来的，注释项使用了自定义颜色，字符串项使用了加粗，其它项都是使用自带的颜色，无样式。

PS：在主编辑窗口拖动选择时还可以看到有字符闪动现象。
PS2：能不能加个设置用来配置嵌套括号着色方案？

**Comment by royqh1979** [comment]
颜色和闪烁 本周末发布的6.3-beta1版本修正。

嵌套括号着色方案做起来比较麻烦，属于工作量不小但是用处不大的工作，暂时没心思做……
