### ISSUE TITLE
建议：增加文件浏览面板

### ISSUE THREAD

**Issue by tiankongsnow** [royqh1979/Dev-CPP#108]
建议在左边的浏览框里再增加一项文件浏览，来浏览和管理指定的文件夹

**Comment by royqh1979** [comment]
嗯，考虑过，不过因为有右键菜单->打开包含的文件夹功能，这个功能的优先级很低。

**Comment by tiankongsnow** [comment]
不是啊，做项目的时候当然添加文件夹就行，但是，dev毕竟面向的还是初学者居多，对初学者来说有几个能做项目呢，多数还是，写一个文件编译一个文件，这时候没有文件管理是非常不方便的。

**Comment by royqh1979** [comment]
不是项目。右键单击编辑的文件，在弹出菜单选择“打开包含的文件夹”，会打开文件浏览器

**Comment by tiankongsnow** [comment]
那样并不方便

**Comment by royqh1979** [comment]
嗯，按照计划，要VirtualTreeView重做结构面板和监视面板，没问题再考虑增加问文件浏览面板

tiankongsnow <notifications@github.com> 于2021年1月4日周一 下午10:36写道：
