### ISSUE TITLE
使用重构的重命名标识符并全部保存后发生异常

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#109]
重命名并全部保存后随便点击主编辑界面的什么位置后会出现异常报告，关闭后会再立即继续出现。
最开始是出现这个报告：
Error info
----------
Version     : 6.2.1
Build Time  : 十二月 12 2020 - 17:38
Message     : Access violation at address 0014A45C in module 'devcpp.exe'. Read of address 00000000
Address     : 0x0014A45C

Machine info
------------
Platform      : Windows NT
OS version    : 6.2 (build 9200)
Computer Name : xxx

Stack trace
-----------
0021C022 (0011B022): TRegExpr.ParseAtom (regexpr - 4194)
0021B339 (0011A339): TRegExpr.ParseAtom (regexpr - 3741)
0021B494 (0011A494): TRegExpr.ParseAtom (regexpr - 3780)
0021B494 (0011A494): TRegExpr.ParseAtom (regexpr - 3780)
0021B37B (0011A37B): TRegExpr.ParseAtom (regexpr - 3741)
0021B3A5 (0011A3A5): TRegExpr.ParseAtom (regexpr - 3752)
0021B204 (0011A204): TRegExpr.ParseAtom (regexpr - 3711)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D65A5 (000D55A5): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D6B0C (000D5B0C): TSynExporterRTF.FormatAttributeInit (SynExportRTF - 175)
001D6CC2 (000D5CC2): GetFontTable (SynExportRTF - 230)
001D6CC2 (000D5CC2): GetFontTable (SynExportRTF - 230)
001B5700 (000B4700): TCustomSynEdit.MouseDown (SynEdit - 2109)
001B5700 (000B4700): TCustomSynEdit.MouseDown (SynEdit - 2109)
001B5700 (000B4700): TCustomSynEdit.MouseDown (SynEdit - 2109)
001B56E0 (000B46E0): TCustomSynEdit.MouseDown (SynEdit - 2109)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)

之后随机出现这两个报告中的其中一个：
Error info
----------
Version     : 6.2.1
Build Time  : 十二月 12 2020 - 17:38
Message     : Access violation at address 0014A45A in module 'devcpp.exe'. Read of address 20205055
Address     : 0x0014A45A

Machine info
------------
Platform      : Windows NT
OS version    : 6.2 (build 9200)
Computer Name : xxx

Stack trace
-----------
0021C022 (0011B022): TRegExpr.ParseAtom (regexpr - 4194)
0021B339 (0011A339): TRegExpr.ParseAtom (regexpr - 3741)
0021B494 (0011A494): TRegExpr.ParseAtom (regexpr - 3780)
0021B494 (0011A494): TRegExpr.ParseAtom (regexpr - 3780)
0021B37B (0011A37B): TRegExpr.ParseAtom (regexpr - 3741)
0021B3A5 (0011A3A5): TRegExpr.ParseAtom (regexpr - 3752)
0021B204 (0011A204): TRegExpr.ParseAtom (regexpr - 3711)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D65A5 (000D55A5): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D6B0C (000D5B0C): TSynExporterRTF.FormatAttributeInit (SynExportRTF - 175)
001D6CC2 (000D5CC2): GetFontTable (SynExportRTF - 230)
001D6CC2 (000D5CC2): GetFontTable (SynExportRTF - 230)
001B77B5 (000B67B5): AddHighlightToken (SynEdit - 3093)
001B86A7 (000B76A7): TCustomSynEdit.PaintTextLines (SynEdit - 3459)
001B8B28 (000B7B28): TCustomSynEdit.PasteFromClipboard (SynEdit - 3550)
001C7A6C (000C6A6C): GetLocalHeaderFileName (CBUtils - 395)
001C7A6C (000C6A6C): GetLocalHeaderFileName (CBUtils - 395)
001C7A6C (000C6A6C): GetLocalHeaderFileName (CBUtils - 395)
001C7A6C (000C6A6C): GetLocalHeaderFileName (CBUtils - 395)
001C7A6C (000C6A6C): GetLocalHeaderFileName (CBUtils - 395)
001C7A6C (000C6A6C): GetLocalHeaderFileName (CBUtils - 395)
001C7A6C (000C6A6C): GetLocalHeaderFileName (CBUtils - 395)
001C70A2 (000C60A2): TSynEditPlugin.Create (SynEdit - 10530)
001B5DAF (000B4DAF): TCustomSynEdit.DoOnGutterClick (SynEdit - 2315)
001B5DAF (000B4DAF): TCustomSynEdit.DoOnGutterClick (SynEdit - 2315)
001B5DAF (000B4DAF): TCustomSynEdit.DoOnGutterClick (SynEdit - 2315)
001B5DAF (000B4DAF): TCustomSynEdit.DoOnGutterClick (SynEdit - 2315)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)
001BD93F (000BC93F): TCustomSynEdit.DragDrop (SynEdit - 5968)

-----------------------------------------------------------------------------------------------------------------

Error info
----------
Version     : 6.2.1
Build Time  : 十二月 12 2020 - 17:38
Message     : Access violation at address 0014A45A in module 'devcpp.exe'. Read of address 6548746E
Address     : 0x0014A45A

Machine info
------------
Platform      : Windows NT
OS version    : 6.2 (build 9200)
Computer Name : xxx

Stack trace
-----------
0021C022 (0011B022): TRegExpr.ParseAtom (regexpr - 4194)
0021B339 (0011A339): TRegExpr.ParseAtom (regexpr - 3741)
0021B494 (0011A494): TRegExpr.ParseAtom (regexpr - 3780)
0021B494 (0011A494): TRegExpr.ParseAtom (regexpr - 3780)
0021B37B (0011A37B): TRegExpr.ParseAtom (regexpr - 3741)
0021B3A5 (0011A3A5): TRegExpr.ParseAtom (regexpr - 3752)
0021B204 (0011A204): TRegExpr.ParseAtom (regexpr - 3711)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D653A (000D553A): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D65A5 (000D55A5): TSynExporterTeX.GetNewCommands (SynExportTeX - 374)
001D6B0C (000D5B0C): TSynExporterRTF.FormatAttributeInit (SynExportRTF - 175)
001D6CC2 (000D5CC2): GetFontTable (SynExportRTF - 230)
001D6CC2 (000D5CC2): GetFontTable (SynExportRTF - 230)
001B77B5 (000B67B5): AddHighlightToken (SynEdit - 3093)
001B86A7 (000B76A7): TCustomSynEdit.PaintTextLines (SynEdit - 3459)
001B8B28 (000B7B28): TCustomSynEdit.PasteFromClipboard (SynEdit - 3550)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)
0023066C (0012F66C): TImportMSVCForm.LocateSourceTarget (ImportMSVCFrm - 200)

**Comment by PlasionX** [comment]
补充一点，不使用全部保存而是手动一个文件一个文件保存就不会触发这个异常。

**Comment by PlasionX** [comment]
再补充一点，在头文件中用重命名标识符重命名结构体字段，C文件里对应的调用不会变，要手动改。

**Comment by royqh1979** [comment]
方便的话把项目打个包发给我？

**Comment by PlasionX** [comment]
[Graph System.zip](https://github.com/royqh1979/Dev-CPP/files/5717888/Graph.System.zip)

**Comment by royqh1979** [comment]
好的，6.3-beta2更新
