### ISSUE TITLE
高分屏下图标显示过小

### ISSUE THREAD

**Issue by hdxrie** [royqh1979/Dev-CPP#111]
希望能改善一下高分屏顶部菜单栏的显示问题
![87JOVRXC2 LHGXORH5OG0SQ](https://user-images.githubusercontent.com/35723869/102678856-12e1bf00-41e6-11eb-84d4-4048634b79c5.png)

**Comment by royqh1979** [comment]
现在的图标是16x16的，确实有点小。希望能有人来帮忙做图标。。。

**Comment by hdxrie** [comment]
我自学过一点ps，可以把图标发过来，我试试看能不能重新绘制一下，但可能需要很久。

**Comment by royqh1979** [comment]
感谢！图标在source\images\newlook目录下，你改了之后直接PR就行。
先看看多大合适，24x24或者32x32？

**Comment by hdxrie** [comment]
最近到期末了，没有时间画图标，要等到我放寒假才有时间画，可能需要一段时间

**Comment by hdxrie** [comment]
图标画完了，我画的64x64，需要重新开一个目录存放，还是把newlook里面的替换掉？

**Comment by royqh1979** [comment]
感谢，已经merge了
考虑了一下，我准备先把程序里面所有出现图标的地方都改成 24 x 24或者 32x32（需要实验）
然后，再单独整一个大图标的工具栏

hdxrie <notifications@github.com> 于2021年2月25日周四 下午6:08写道：
