### ISSUE TITLE
函数调用前紧跟着强制转换会导致解析错误

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#122]
如
> char *str = (char *)calloc(num, sizeof(char));

ctrl+左键点击calloc时会显示“找不到表达式“char *calloc”的信息”。
不过写成
> char *str = (char *) calloc(num, sizeof(char));

就可以正常解析了。

**Comment by PlasionX** [comment]
> #include<>

也会导致无法自动补全头文件，另外似乎头文件补全不会区分<>和""。

**Comment by royqh1979** [comment]
头文件补全现在是区分<>和""的。但是需要当前文件已经保存，devcpp知道它的路径才能找到同一个文件夹下的头文件

PlasionX <notifications@github.com> 于2020年12月29日周二 下午3:44写道：

**Comment by royqh1979** [comment]
嗯，这块儿 是个大坑，比如 x->y能提示， x -> y 就没有提示，我得好好考虑一下怎么处理
PlasionX <notifications@github.com> 于2020年12月29日周二 下午2:53写道：

**Comment by royqh1979** [comment]
暂时先不管 x -> y这种了，先能正确处理你这种情况吧

Roy Qu <royqh1979@gmail.com> 于2020年12月29日周二 下午5:07写道：
