### ISSUE TITLE
typedef struct/enum换行发生异常

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#130]
输入“typedef struct”或“typedef enum”再按下换行会触发异常，如果此时再删掉换行又会触发一次，报告如下：
Error info
----------
Version     : 6.3-beta3
Build Time  : 一月 1 2021 - 15:10
Message     : List index out of bounds (11)
Address     : 0x0011DD96

Machine info
------------
Platform      : Windows NT
OS version    : 6.2 (build 9200)
Computer Name : xxx

Stack trace
-----------
002200D6 (0011F0D6): TFindForm.Execute (FindFrm - 118)
0021F3ED (0011E3ED): TRegExpr.DumpOp (regexpr - 6443)
0021F548 (0011E548): TRegExpr.DumpOp (regexpr - 6443)
0021F548 (0011E548): TRegExpr.DumpOp (regexpr - 6443)
0021F42F (0011E42F): TRegExpr.DumpOp (regexpr - 6443)
0021F459 (0011E459): TRegExpr.DumpOp (regexpr - 6443)
0021F2B8 (0011E2B8): TRegExpr.DumpOp (regexpr - 6443)
001CE621 (000CD621): TCppParser.CheckForMethod (CppParser - 873)
001CE621 (000CD621): TCppParser.CheckForMethod (CppParser - 873)
001CE621 (000CD621): TCppParser.CheckForMethod (CppParser - 873)
001D2FC0 (000D1FC0): TCppParser.ScanMethodArgs (CppParser - 3001)
001D4A5B (000D3A5B): TCodeCompletion.SetPosition (CodeCompletion - 481)
001D4DF1 (000D3DF1): TSynCustomExporter.Clear (SynEditExport - 282)
001D5E32 (000D4E32): TSynExporterTeX.AttriToCommand (SynExportTeX - 241)
001C5722 (000C4722): TCustomSynEdit.BufferToDisplayPos (SynEdit - 9613)
001B39A1 (000B29A1): TCustomSynEdit.PixelsToNearestRowColumn (SynEdit - 1106)
001B39A1 (000B29A1): TCustomSynEdit.PixelsToNearestRowColumn (SynEdit - 1106)
001C0FF3 (000BFFF3): TCustomSynEdit.DoOnCommandProcessed (SynEdit - 7208)
001C0FFB (000BFFFB): TCustomSynEdit.DoOnCommandProcessed (SynEdit - 7209)
001BDDFC (000BCDFC): TCustomSynEdit.EnsureCursorPosVisibleEx (SynEdit - 6180)
001BDDFC (000BCDFC): TCustomSynEdit.EnsureCursorPosVisibleEx (SynEdit - 6180)
001B48DD (000B38DD): TCustomSynEdit.GetSelText (SynEdit - 1615)
001B48DD (000B38DD): TCustomSynEdit.GetSelText (SynEdit - 1615)
001B4860 (000B3860): CopyPaddedAndForward (SynEdit - 1595)
00268518 (00167518): TProject.RebuildNodes (Project - 1703)
001BD11B (000BC11B): TCustomSynEdit.SetBookMark (SynEdit - 5584)

**Comment by PlasionX** [comment]
此外，输入

> typedef enum
> {
> } E;

会导致IDE判定“}”和“E”为枚举的元素，影响结构标签和代码染色。

**Comment by royqh1979** [comment]
ok
