### ISSUE TITLE
切换注释无法从注释恢复代码

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#131]
对已使用切换注释的代码使用切换注释会再加一层注释而不是去掉注释。

**Comment by royqh1979** [comment]
给我一段有问题的代码？我试了一下没发现你说的问题？

PlasionX <notifications@github.com> 于2021年1月5日周二 上午4:19写道：

**Comment by PlasionX** [comment]
我这是任何代码都会。
[Project Test.zip](https://github.com/royqh1979/Dev-CPP/files/5767535/Project.Test.zip)
对已注释的printf，无论块选择还是光标放在行上，都只会再加一层注释。
