### ISSUE TITLE
长时间使用时随机出现非法地址写入异常

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#138]
未按其它任何按键时，鼠标左键点击编辑窗口触发，触发时编辑窗口光标前的文本会全部被选中，然后弹窗提示：
Access violation at address 00233FA7 in module 'devcpp.exe'. Write of address 67D65988.
确定后会立即弹出第二个，第一个地址不变，第二个在十几范围内变化。

**Comment by royqh1979** [comment]
还能想起来选中的文本是啥内容吗？。。。点的是窗口的左边，还是右边，上部还是下部，是否接近行号折叠线，等等？

**Comment by royqh1979** [comment]
点击之前最后的操作是啥？中间大概间隔多长时间？

**Comment by PlasionX** [comment]
似乎是要粘贴，源是同文件的其它地方的代码，但忘了是粘贴前还是后了；选中的是光标位置前面的全部文本(不清楚是不是从文件开头开始，总之就是编辑屏幕上半部分都是蓝的)

**Comment by royqh1979** [comment]
暂时复现不了这个问题。但是正好要改鼠标处理事件，在编辑器左侧行号栏拖动不会再触发断点切换和代码折叠处理；反过来单击鼠标也不会触发选择代码块处理。先继续观察看看吧
