### ISSUE TITLE
调试的时候看不到值

### ISSUE THREAD

**Issue by 18767752565** [royqh1979/Dev-CPP#147]
定义了一个全局变量二维数组int f[501][501];
然后初始化：
fill(f[0],f[0]+250000,INT_MAX);

调试的时候看不到f的值，提示error

**Comment by royqh1979** [comment]
devcpp使用gdb来进行调试，当要输出的值占用内存超过一定数量时，就会报错。如果你确定需要在局部变量或者监视窗口查看整个f数组的内容，可以在调试开始后，在gdb主控台中输入“set
max-value-size unlimited"，然后继续调试就可以看到完整的内容了。


不过我建议你还是用监视或者求值功能来查看f具体某个元素的值



zhuang <notifications@github.com> 于2021年2月8日周一 上午6:29写道：

**Comment by 18767752565** [comment]
好的 谢谢  后来重新安装一次又可以看到了 不知道为什么。
另外 我发现使用c++stl的队列 栈 vector 这些数据结构的时候，里面有些看不懂的信息，值没有显示，好像不方便。
