### ISSUE TITLE
建议增加查看stl的队列 栈 vector 等调试的值

### ISSUE THREAD

**Issue by 18767752565** [royqh1979/Dev-CPP#150]
单步调试的时候stl的队列 栈 vector 等信息无法显示，不方便，建议增加  谢谢。

**Comment by royqh1979** [comment]
现在的调试功能实际上就是对gdb的封装；要增加这个功能需要引入gdb的python扩展，但是会导致整个gcc工具链占用的空间增加将近1倍（400M -> 将近1G)。以小熊猫devcpp的定位（轻便小巧的学习用开发IDE），这太大了。

如果你需要查看某个vector的内容，可以在监视窗口里面加入下面的式子：
*(vec._M_impl._M_start)@vec.size()

**Comment by 18767752565** [comment]
好的&nbsp; 谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "royqh1979/Dev-CPP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月21日(星期天) 晚上9:33
收件人:&nbsp;"royqh1979/Dev-CPP"<Dev-CPP@noreply.github.com&gt;;
抄送:&nbsp;"??"<546094038@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [royqh1979/Dev-CPP] 建议增加查看stl的队列 栈 vector 等调试的值 (#150)





 
现在的调试功能实际上就是对gdb的封装；要增加这个功能需要引入gdb的python扩展，但是会导致整个gcc工具链占用的空间增加将近1倍（400M -&gt; 将近1G)。以小熊猫devcpp的定位（轻便小巧的学习用开发IDE），这太大了。
 
如果你需要查看某个vector的内容，可以在监视窗口里面加入下面的式子：
 *(vec._M_impl._M_start)@vec.size()

**Comment by royqh1979** [comment]
其实你也可以自己安装MinGW-w64 gcc，用它的gdb
