### ISSUE TITLE
Could not disable parameter '-fexec-charset=gbk' when using Clang?

### ISSUE THREAD

**Issue by Local-System** [royqh1979/Dev-CPP#166]
I downloaded a copy of MinGW 10.2.0 on WinLibs with Clang++. I have tried to compile the code directly using Clang++, and it was successfully compiled. But when I was trying to use Clang++ to compile my program on Red Panda Dev-C++ 6.7-beta1.1, the compiler clang++.exe reported `invalid value 'gbk' in '-fexec-charset=gbk'` and terminated the compilation. What's worse, I could not find the switch to disable it. Where is the switch to disable or change the parameter `-fexec-charset=gbk` ,or will it be added in the future releases?

**Comment by royqh1979** [comment]
I've never used Dev-C++ with clang; at least Dev-C++'s debug functions won't work.

But yes, I'll add an option to turn off the charset option
