### ISSUE TITLE
编译器配置不能正确保存

### ISSUE THREAD

**Issue by KsharpMoring** [royqh1979/Dev-CPP#177]
OS：Windows 10 x64
软件版本：6.6

在「编译器选项」界面中，选择「由文件夹添加编译器设置」，我在这里添加了自己安装的MinGW-w64的编译器，然后当我关闭软件并再次打开时，软件提示「在验证编译器设置“<配置名称>”发现存在以下问题：未指定二进制（bin）目录……」

我自己分析了一下，得出这些信息，：

- 首先，所谓的编译器配置是存储在 devcpp.ini 这个文件里的，里面记录了每个配置的详细内容，一个配置为一节，以 [CompilerSets_xxx] （xxx是自动生成的编号）作为一节的名字；
- 然后，每个配置的名称，以及当前选中哪一个配置，则是在 [CompilerSets] 节中；

-  我观察了文件内容，发现：当我使用上述方法添加了编译器配置，并退出软件之后，配置文件的 [CompilerSets] 这一节中出现了`3=MinGW GCC8.1.0 64-bit Release` 这一行，表示3号配置的名字叫 "MinGW GCC8.1.0 64-bit Release"，但是，整个文件里本该出现的 [CompilerSets_3] 这一节，**却并没有出现，也就是说，"MinGW GCC8.1.0 64-bit Release" 这个配置没有被保存，而是丢失了**。此时，如果 [CompilerSets] 节的 Current 键刚好被设置为3（也就是当前选的配置，恰好就是没有被保存的这个配置），打开软件时就会显示「在验证编译器设置“MinGW GCC8.1.0 64-bit Release”发现存在以下问题：未指定二进制（bin）目录……」（_**所以实际上这个提示也不是特别准确，这岂止是未指定目录啊，这是整个配置内容都丢失了呀。。。**_）
- 实际上也没有全部丢失，如果是从文件夹添加的编译器配置，他会一次性生成三个配置，一个release，一个debug，一个profiling，我遇到的情况是只有release丢失了，另外两个是好的
- 我的 devcpp.ini 的路径是C:\\Users\\(此处为5个数字)\\AppData\\Roaming\\Dev-Cpp\\devcpp.ini 
- 使用「由文件夹添加编译器设置」时，我选择的路径是 C:\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64

**Comment by royqh1979** [comment]
先试一下6.7-beta4看看是否有这个问题

**Comment by SciUnivMoring** [comment]
> 先试一下6.7-beta4看看是否有这个问题

问题在6.7-beta4还是存在，不过我可能发现问题出在哪了。
**必须在「编译器选项」界面中选中一个配置，然后点击「确定」，这个配置才会被写入到 devcpp.ini**。

使用「由文件夹添加编译器设置」时，我选中一个文件夹，它会基于这个编译器自动添加三个配置（release，debug，profiling），然后此时会自动选中其中一个（比如选中debug），如果这时点了确定，就只有此时被选中的那个配置（debug配置）会被保存，而另外两个（release和profiling），就处于“保存了，但也没保存”的状态，如果这时再打开「编译器选项」界面，选中release，点确定，才能保证release配置也被保存了；再打开界面，选中profiling，点确定，才能保证profiling配置也被保存了。如果你不这么做，当你关闭软件再打开，release和profiling这两个编译配置就丢失了（配置名称还在，你可以选中这个配置，但是配置的内容没有了），于是就会出现「在验证编译器设置“<配置名称>”发现存在以下问题：未指定二进制（bin）目录……」。

**Comment by royqh1979** [comment]
6.7正式版已修正此问题
