### ISSUE TITLE
Include directory in LIBS, not in INCS

### ISSUE THREAD

**Issue by petervarley** [royqh1979/Dev-CPP#179]
I added an include directory, but in the makefile it is in LIBS, not in INCS
![Screenshot (226)](https://user-images.githubusercontent.com/65538474/119329116-c743ad80-bc7c-11eb-8cb9-04a966e416aa.png)
[Makefile.win.txt](https://github.com/royqh1979/Dev-CPP/files/6531376/Makefile.win.txt)

**Comment by royqh1979** [comment]
yes, the title of the tabs are wrong.
The first tab is for libs, and the second one is for includes. Like the order in the global compiler options dialog.
I'll fix them in the next version
