### ISSUE TITLE
Problem with TDM-GCC

### ISSUE THREAD

**Issue by flopezre** [royqh1979/Dev-CPP#180]
Hello everyone, well that is my problem, i make a gif:
![Animation](https://user-images.githubusercontent.com/4932575/119444847-e16fa100-bcf9-11eb-90d1-53a7f34da10d.gif)
Cheers

**Comment by royqh1979** [comment]
It's because by default TDM-GCC will install locale files for gcc, and the output of gcc is translated, which can't be parsed by dev-cpp.
For now, you can remove all the files in the TDM-GCC-xxx/share/locale, and re-detect the compiler set

**Comment by flopezre** [comment]
Works, thanks
