### ISSUE TITLE
调试报错或无法启动, 退出Dev-C++重新打开后正常

### ISSUE THREAD

**Issue by hlizard** [royqh1979/Dev-CPP#201]
![image](https://user-images.githubusercontent.com/6994037/129660800-a394e6c9-9f88-44ea-bdf0-084ac807ed0d.png)

我32位win7, 和64位win10都遇到了, 且和项目无关, 都是直接运行新建模版项目.

**Comment by royqh1979** [comment]
fixed in 6.7.5
