### ISSUE TITLE
显示行号的情况下屏幕阅读器无法读取代码编辑区

### ISSUE THREAD

**Issue by cary-rowen** [royqh1979/Dev-CPP#208]
如题，如果设置了显示行号，使用 NVDA 屏幕阅读器则无法朗读代码编辑区。
NVDA（免费且开源的屏幕阅读器，可帮助视障用户使用计算机）其 github： https://github.com/nvaccess/nvda

**Comment by royqh1979** [comment]
这个不是Dev-Cpp去解决的问题吧？

**Comment by cary-rowen** [comment]
具体原因未知，原版 dev-CPP不存在此问题，另外，屏幕阅读器通过 MSAA 以及 UIA 等接口实现与应用程序的交互，如果某些控件没有实现相应 accessibility 接口则无法访问。

**Comment by cary-rowen** [comment]
Currently I don't seem to see developers willing to fix this bug, so closed.
