### ISSUE TITLE
新版打开文件，编辑页是空白

### ISSUE THREAD

**Issue by pqwer99** [royqh1979/Dev-CPP#26]
新版打开文件，编辑页是空白

**Comment by royqh1979** [comment]
能说的更详细些吗？
1.是用的6 beta2版本吗？
2.是通过”文件“菜单中的“项目或者文件“项，或者工具栏中的”项目或者文件“按钮来打开文件的吗？
3.是偶尔出现这个问题还是总是这样？
4.和打开的文件或者文件所在的位置有关吗？换个文件或者换个文件夹还是同样问题吗？

**Comment by pqwer99** [comment]
5.15beta5没问题。
又测试了一下：
1.是6 beta2
2.通过菜单和工具栏都存在这个问题
3.总是为样
4.换过，问题一直存在
从没看见过文件内容
测试环境：win7sp1, winxpsp3, win2003sp2，都是32位
我用bds2006编译后也是这个问题。
提个建议，在高DPI下：菜单项高度不够（16），像g字母下面部分被挡住。工具栏编译器选项显示不全tbCompilers没能放下cmbCompilers。 tools configure 窗体右边和下边也被挡住，拖放也无法看到右边的button.

**Comment by royqh1979** [comment]
我这边没法复现这个问题。是所有文件都无法打开？

**Comment by royqh1979** [comment]
我这边无法复现这个问题。能给个截图或者视频吗？或者能否把要打开的文件发一个上来？
Delphi 7对高DPI支持还是不行，菜单项和工具栏的高度是定死的。
下一个版本考虑改成新版Delphi，但是不知道XP兼容性如何。

**Comment by royqh1979** [comment]
我这里6 Beta 2打开文件的视频
https://www.bilibili.com/video/BV1Ky4y1r7RY/
没有问题

**Comment by pqwer99** [comment]
其实在我电脑上任意文件都是这样

**Comment by royqh1979** [comment]
我用Windows 10, Win 7 sp1 64位，winxp sp3测试都没有打不开的问题？

**Comment by royqh1979** [comment]
方便的话加个QQ？

**Comment by royqh1979** [comment]
远程看一下？

**Comment by pqwer99** [comment]
QQ: 9834942




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pyscripter"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 中午11:51
收件人: "royqh1979/Dev-CPP"<Dev-CPP@noreply.github.com&gt;; 
抄送: "老枪"<9834942@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [royqh1979/Dev-CPP] 新版打开文件，编辑页是空白 (#26)





 
远程看一下？
 
&mdash;

**Comment by pqwer99** [comment]
9834942




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pyscripter"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 中午11:51
收件人: "royqh1979/Dev-CPP"<Dev-CPP@noreply.github.com&gt;; 
抄送: "老枪"<9834942@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [royqh1979/Dev-CPP] 新版打开文件，编辑页是空白 (#26)





 
远程看一下？
 
&mdash;

**Comment by royqh1979** [comment]
好了，定位问题，在windows 7/xp下用UTF-8转码失败
