### ISSUE TITLE
switch from synedit to Scintilla ? worth to try ?

### ISSUE THREAD

**Issue by armgong** [royqh1979/Dev-CPP#52]
IMHO Scintilla  better than synedit ,and many project use it as syntax editor , for example innosetup use it and has a compenent wrap Scintilla , code  at https://github.com/jrsoftware/issrc/blob/main/Components/ScintEdit.pas.

I  konw replace synedit will need lots work , but it good for furtue ,  maybe worth to try .

**Comment by royqh1979** [comment]
Now Dev-C++ is deeply integrated with synedit. Switch to scintilla almost
means to write it all over again. That's really a lot of work...

Yu Gong <notifications@github.com> 于2020年11月1日周日 上午12:32写道：

**Comment by armgong** [comment]
Seven or eight years ago, I try it once and abort , really a lot works, but it doable . maybe one day will try it again, maybe then abort agin :) :)
