### ISSUE TITLE
修改快捷键时出现错误

### ISSUE THREAD

**Issue by wylovecat** [royqh1979/Dev-CPP#61]
在修改快捷键时会出现报错，无论是增加新的快捷键还是删除快捷键都会出现。在关闭程序后，重新打开时，会出现同样的报错，且程序无法正常打开。卸载软件重新安装的话，如果不删除配置文件依然出现同样的问题，无法正常打开。需要卸载时删除配置文件进行重新安装才能正常打开程序。多次尝试均可复现这个错误。报错信息如下：
Error info
----------
Version     : 6
Build Time  : 十一月 7 2020 - 11:14
Message     : Access violation at address 77850848 in module 'ntdll.dll'. Write of address 0010555D
Address     : 0x77850848

Machine info
------------
Platform      : Windows NT
OS version    : 6.2 (build 9200)
Computer Name : DESKTOP-U7ESP12

Stack trace
-----------
001F06B6 (000EF6B6): TExceptionFrm.GetStackReport (ExceptionFrm - 402)
001EF9CD (000EE9CD): TEAnalyzer.EHandler (ExceptionFrm - 146)
001EFB28 (000EEB28): TEAnalyzer.EHandler (ExceptionFrm - 155)
001EFB28 (000EEB28): TEAnalyzer.EHandler (ExceptionFrm - 155)
001EFA0F (000EEA0F): TEAnalyzer.EHandler (ExceptionFrm - 153)
001EFA39 (000EEA39): TEAnalyzer.EHandler (ExceptionFrm - 153)
001ED1A0 (000EC1A0): TdevShortcuts.Load (devShortcuts - 215)
001ED1A0 (000EC1A0): TdevShortcuts.Load (devShortcuts - 215)
001ED1A0 (000EC1A0): TdevShortcuts.Load (devShortcuts - 215)
001ED1A0 (000EC1A0): TdevShortcuts.Load (devShortcuts - 215)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
0022068E (0011F68E): TFindForm.btnExecuteClick (FindFrm - 280)
001ED0F5 (000EC0F5): TdevShortcuts.Load (devShortcuts - 191)
0024AB33 (00149B33): TMainForm.FormCreate (main - 6227)

**Comment by royqh1979** [comment]
嗯，是因为有一个新加的Action没设标题
增加了相应的判断，如果没标题(Caption为空）就用它的Name作为配置文件的关键字

**Comment by royqh1979** [comment]
已修正，等下周新版发布，或者加QQ群我把最新版发给你看一下
