### ISSUE TITLE
能不能添加一个选项来切换不同的自动配对括号风格

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#67]
能不能加一个选项来使用5.11版本的括号配对？实在不习惯输入左大括号再输入回车后，右大括号不是在光标下一行。而且#include的尖括号配对也没了。

**Comment by royqh1979** [comment]
下个版本里在{}中间输入回车会变成
{
缩进 光标当前位置
}
这样的形式。
#include 尖括号配对也有了（以及右尖括号自动跳过）
