### ISSUE TITLE
有空格的项目名会导致连接时无法正常连接标准库

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#69]
![image](https://user-images.githubusercontent.com/70289464/99184899-6002e900-2781-11eb-83c2-0840a0fd39ab.png)

**Comment by royqh1979** [comment]
你使用的版本？我试着建了几个名称含空格的项目编译没问题

大概不是项目名空格的问题。方便的话能把项目打个包发给我看看吗？

**Comment by royqh1979** [comment]
方便的话，能否麻烦你先试试6.1-beta1有没有同样的问题？印象中6.1-beta1里修正了一些关于Project构建的问题

**Comment by royqh1979** [comment]
> 方便的话，能否麻烦你先试试6.1-beta1有没有同样的问题？印象中6.1-beta1里修正了一些关于Project构建的问题

在这里 https://github.com/royqh1979/Dev-CPP/releases/tag/v6.1-beta1.1

**Comment by PlasionX** [comment]
还是一样。
这是工程文件 [Project.zip](https://github.com/royqh1979/Dev-CPP/files/5542678/Project.zip)

**Comment by PlasionX** [comment]
另外对于带结构体的文件，左侧结构菜单会无法解析；而且有时候会出现输入 "结构体变量->" 时出现的是代码补全而不是字段显示的情况。

**Comment by royqh1979** [comment]
> 还是一样。
> 这是工程文件 [Project.zip](https://github.com/royqh1979/Dev-CPP/files/5542678/Project.zip)

我看了一下，你这个项目应该是用Dev-C++ 5.11以前版本创建的。项目文件兼容性可能有点问题

项目属性里面勾选了不链接标准库
![no-stdlib](https://user-images.githubusercontent.com/8803140/99202091-fe766500-27e8-11eb-9fc9-ea2906dd1808.png)

把这个改成no编译就没问题了

**Comment by royqh1979** [comment]
> 而且有时候会出现输入 "结构体变量->" 时出现的是代码补全而不是字段显示的情况。

能否把出现这个问题的代码文件，和出现问题的具体位置（行，列）告诉我看一下

**Comment by royqh1979** [comment]
> 另外对于带结构体的文件，左侧结构菜单会无法解析；

关于左侧菜单的问题，有一部分的原因是因为你的头文件名是Code.h，但是包含的时候写的是#include "code.h"

我在新版本里改为文件名不区分大小写了

**Comment by PlasionX** [comment]
> > 而且有时候会出现输入 "结构体变量->" 时出现的是代码补全而不是字段显示的情况。
> 
> 能否把出现这个问题的代码文件，和出现问题的具体位置（行，列）告诉我看一下

是Cache.c的createCache()，但是我现在只要保存这个文件或在createCache()里打“c”就会程序未响应，然后CPU占用很高。版本是6.1-beta1。
![image](https://user-images.githubusercontent.com/70289464/99213312-41940080-2808-11eb-8517-47ea36618524.png)

**Comment by royqh1979** [comment]
[devcpp.zip](https://github.com/royqh1979/Dev-CPP/files/5544474/devcpp.zip)
针对你的问题做了修改，方便的话试一下？

**Comment by royqh1979** [comment]
能否麻烦你试一下刚发布的6.1-beta2？

https://github.com/royqh1979/Dev-CPP/releases/tag/v6.1-beta2

**Comment by PlasionX** [comment]
原先的问题解决了，但是发现了新的问题。首先是结构体内嵌结构体的时候，输入"结构体变量->子结构体字段->"时(->和.都一样)，代码补全框会一闪而过，无法正常工作；其次是内嵌结构体必须用typedef定义别名并使用别名来声明字段，如果用struct XXX来声明会导致输入"结构体变量->"时不显示内嵌结构体字段；最后，快捷键全部失效了。
![image](https://user-images.githubusercontent.com/70289464/99238795-2390c500-2835-11eb-8617-f05510d5ede3.png)
![image](https://user-images.githubusercontent.com/70289464/99238853-34413b00-2835-11eb-88e4-676d65ce4861.png)

**Comment by royqh1979** [comment]
谢谢。快捷键的问题我会尽快发布新版

struct BBB xxx;这种定义目前会被当作前置结构声明处理； 这是因为之前devcpp在解析代码时不做宏展开，而标准库中很多这样的形式的前置声明，作为变量定义处理的话会出问题；

6.1-beta1开始做了宏展开，但是这块儿如果修改的话需要仔细测试，我打算放到6.1正式版发布之后再说
