### ISSUE TITLE
在调试模式下运行的程序访问非法地址会导致IDE关闭工程出错

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#73]
> #include<stdio.h>
> #include<stdlib.h>
> 
> struct A
> {
> 	int n;
> };
> 
> int main()
> {
> 	struct A *test = NULL;
> 	printf("%d", test->n);
> 	return 0;
> }
> 
在调试模式下调试这个程序，在运行到printf()后会报错，然后点停止执行后再尝试关闭工程(或者直接关闭IDE也会)会导致弹框，内容为“Access violation at address 0023664D in module 'devcpp.exe'. Write of address 00000080.”。

**Comment by royqh1979** [comment]
你用的哪个版本？我在6.1-beta2.2下没有这个问题？

**Comment by PlasionX** [comment]
beta2.2，要建工程

**Comment by royqh1979** [comment]
你建的是什么类型的工程？

PlasionX <notifications@github.com> 于2020年11月17日周二 下午7:32写道：

**Comment by royqh1979** [comment]
你把整个项目打个包发给我看看吧。我自己建项目没有出现这个问题？

Roy Qu <royqh1979@gmail.com> 于2020年11月17日周二 下午8:28写道：

**Comment by PlasionX** [comment]
[Test.zip](https://github.com/royqh1979/Dev-CPP/files/5553587/Test.zip)
刚刚又试了下，要用单步进入运行printf()，用单步执行是没问题的。

**Comment by royqh1979** [comment]
我用你的试也没有那个问题。你用的啥操作系统？windows 7？

PlasionX <notifications@github.com> 于2020年11月17日周二 下午9:05写道：

**Comment by PlasionX** [comment]
win10 1909

**Comment by royqh1979** [comment]
我觉得大概不是指针的问题？ 我在新版本里改了一些调试器的问题，如果现在这个问题不影响一般使用的话，等新版发布你再看看是不是还有这个问题？

PlasionX <notifications@github.com> 于2020年11月17日周二 下午10:51写道：

**Comment by PlasionX** [comment]
好的

**Comment by royqh1979** [comment]
下次不用关issue，先放在那里好了

PlasionX <notifications@github.com> 于2020年11月17日周二 下午11:21写道：
