### ISSUE TITLE
调试模式的数值显示功能不稳定

### ISSUE THREAD

**Issue by PlasionX** [royqh1979/Dev-CPP#86]
IDE版本为6.1 beta2-2，在工程[Hufferman Encode Decode.zip](https://github.com/royqh1979/Dev-CPP/files/5566062/Hufferman.Encode.Decode.zip)的Main.c的第597行打下断点，调试运行时分别输入2和[data.txt](https://github.com/royqh1979/Dev-CPP/files/5566077/data.txt)文件的路径运行到断点，然后鼠标在597到601行代码上快速晃动(即高频率使用数值显示功能)时非常容易导致IDE未响应。

**Comment by royqh1979** [comment]
嗯嗯，beta3修正了这个问题，已经在QQ群里内测了。如果没啥问题明后天发布

**Comment by royqh1979** [comment]
6.1 beta3发布了，你可以试试

**Comment by PlasionX** [comment]
没有再出现了
