### ISSUE TITLE
default project wrong when create new project 

### ISSUE THREAD

**Issue by armgong** [royqh1979/Dev-CPP#90]
when create new project ,the default dir is your user name  
<img width="404" alt="捕获" src="https://user-images.githubusercontent.com/4819374/99870344-59ef8b00-2c0d-11eb-92c6-2c1024425a43.PNG">

**Comment by armgong** [comment]
edit config.ini solve this issue , but don't know why your user dir in config.ini,and search in source code ,there is no hard-code user dir , maybe introduced by old version?

**Comment by royqh1979** [comment]
This is a feature introduced in 6 beta3.
If your devcpp is installed by installer, it will use user's document
folder as the default folder for projects.

in 6.1, if your devcpp is not installed(portable version), it will use
dev-cpp/projects folders as the default. (So it's really portable)

And in the next version i'll add an option in config.ini (and the
environment dialog) for the default project folder.


Yu Gong <notifications@github.com> 于2020年11月21日周六 下午3:33写道：
